name: Check dependencies of rendered ZIPs

on:
  pull_request:

jobs:
  updatecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Check dependencies
        shell: bash
        run: ./update_check.sh
